# Site Infos
title: Grace Ning 
description: Hey, I'm a web developer and freelance artist studying Computer Engineering at the University of Waterloo 
keywords: grace,ning,developer,freelance,artist,web,design,portfolio,waterloo,computer,engineering

baseurl: ""
url: http://www.gracening.me

sass:
  style: compressed
  sass_dir: _sass

markdown: kramdown
